name: ZMK Firmware Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left
          - board: nice_nano_v2
            shield: corne_right

    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install west
        run: |
          python -m pip install --upgrade pip
          pip install west

      - name: West init/update (explicit manifest URL)
        run: |
          rm -rf .west zmk zephyr modules || true
          west init -m https://github.com/osirispc/zmk-config-albert.git --mr main .
          west update
          ls -la
          ls -la zmk
          ls -la zmk/app

      - name: Build
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- \
            -DZMK_CONFIG=${{ github.workspace }}/config \
            -DSHIELD=${{ matrix.shield }}

      - name: Rename UF2
        run: |
          cp build/zephyr/zmk.uf2 ./${{ matrix.shield }}-${{ matrix.board }}.uf2

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}-${{ matrix.board }}
          path: |
            ${{ matrix.shield }}-${{ matrix.board }}.uf2
